media: src/assets/*
content: 
  - name: art
    label: Art
    type: collection
    path:  src/content/art
    fields: 
      - { name: title, label: Title, type: string}
      - { name: date, label: Date, type: date}
      - { name: image, label: image, type: image}
      - { name: body, label: Body, type: rich-text}